### ISSUE TITLE
webpack 2 command line arguments are lost

### ISSUE THREAD

**Issue by PavelPolyakov** [Fitbit/webpack-config#84]
Hi, 

Webpack 2 dictates the way of passing custom command line arguments:
https://github.com/webpack/webpack/issues/2254

So we can have dynamic configs.

I've tried to apply the same logic to the configs which are processed using `webpack-config`, but found that it doesn't work as expected.

Here is the repository to reproduce the issue:
https://github.com/PavelPolyakov/webpack-config-env-issue

Basically, when I run webpack and pass the variable `env.hello`, I want my `base` config to be extended. 

During the run, I see that it is invoked twice, first time the env variable is there, but the second time I have some `Config` object.

![image](https://cloud.githubusercontent.com/assets/839290/25043312/3aa36f8e-211f-11e7-8020-dfc5f3a96822.png)

I'd appreciate a help, maybe I'm doing something wrong.

Regards,

**Comment by PavelPolyakov** [comment]
hi @mdreizin, do you think it's an incorrect behaviour or I do something wrong?

**Comment by ianks** [comment]
Experiencing the same issue. The first time the configuration is called, things work correctly. After that, the env arguments from the cli are lost

**Comment by mdreizin** [comment]
@PavelPolyakov @ianks I'm really sorry that you were waiting for long time. I didn't have free time to contribute this project.

Please update to `7.1.0` and let me know whether it works for your or not.

**Comment by davidhouweling** [comment]
Sorry to comment on an old issue but seems relevant... @mdreizin from within a `merge` function, how do we access the custom webpack `--env.*` values?
