### ISSUE TITLE
not working with webpack 3.5.1

### ISSUE THREAD

**Issue by RahavLussato** [Fitbit/webpack-config#96]
after upgrading webpack to 3.5.1 i got this error:
![screen_shot_2017-08-08_at_17_35_09](https://user-images.githubusercontent.com/6713560/29077151-0ebbc9e2-7c60-11e7-8ff4-2e399caf8e4b.png)

**Comment by RahavLussato** [comment]
seems like it related UglifyJS plugin for webpack i also upgraded it to its last beta in order to have it work with the new webpack.

**Comment by mdreizin** [comment]
@RahavLussato Could you please provide a minimal repo to reproduce this issue?

**Comment by RahavLussato** [comment]
@mdreizin https://github.com/RahavLussato/webpack-config-env-issue

**Comment by mdreizin** [comment]
@RahavLussato I have just replaced `UglifyJSPlugin` with `webpack.optimize.UglifyJsPlugin` and everything works fine. It looks like that is issue of `uglifyjs-webpack-plugin`:

```js

try {
    new UglifyJSPlugin({
        mangle: {
            except: ['$super', '$', 'exports', 'require']
        },
        sourceMap: true,
        compress: {
            warnings: false
        }
    })
} catch(err) {
    console.log(err)
}
```

It will produce the following error: 

```
{ [Error: Validation Error

UglifyJs Plugin Invalid Options

options['mangle'] should NOT have additional properties
options['compress'] should NOT have additional properties
]
  err: 
   [ { keyword: 'additionalProperties',
       dataPath: '[\'mangle\']',
       schemaPath: '#/additionalProperties',
       params: [Object],
       message: 'should NOT have additional properties' },
     { keyword: 'additionalProperties',
       dataPath: '[\'compress\']',
       schemaPath: '#/additionalProperties',
       params: [Object],
       message: 'should NOT have additional properties' } ] }
```

**Comment by RahavLussato** [comment]
@mdreizin thanks, i think that on cases like that you should raise the same exception so it will be easy to understand if its related to `webpack-config` or not

**Comment by mdreizin** [comment]
@RahavLussato From my point of view this case should be handled by webpack-cli, for instance through https://nodejs.org/api/process.html#process_event_uncaughtexception.
